version: "3.9"

services:
  # ─────────────────────────── Django ──────────────────────────
  web:
    build:
      context: .
      dockerfile: Dockerfile           # same Dockerfile you already have
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code                        # live-reload during dev
    env_file: .env                     # DB creds, PUBLIC_URL, etc.
    depends_on:
      - db
    expose:                            # only to internal network
      - "8000"
    restart: always

  # ────────────────────────── Postgres ─────────────────────────
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB:       ${DB_NAME}
      POSTGRES_USER:     ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data

  # ─────────────────────────── Nginx ───────────────────────────
  nginx:
    image: nginx:alpine
    container_name: fra-nginx
    restart: always
    ports:
      - "443:443"                      # https://192.168.x.x/
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/ssl/fra:ro        # cert.pem & key.pem live here
    depends_on:
      - web

volumes:
  pgdata:
