# Generated by Django 5.2 on 2025-06-28 16:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_offering_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offering',
            unique_together={('subject', 'trimester', 'lecturer', 'section')},
        ),
    ]
